spring:
  application:
    name: BOOK-SERVICE
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8081/eureka

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8082
